### PR TITLE
add Admin Panel template

### PR DESCRIPTION
**Pull request by swag**
This isn't perfect but it's a good start. A couple things I couldn't figure out how to do:

- Use a Form component - this component didn't work for me locally (red underline in VS Code even after importing component)
- I want to update the Customers Table to have a new Contact Name if someone updates it in the adjacent Card - couldn't figure out how to use Refetch for this

### CODE REVIEW

**Comment by rose-huang** [comment]
@swag Hi Ravi! I can take a look at adding the form component and card and update your PR. We just released a version of views a few days ago with Forms

**Comment by joshma** [comment]
removing myself from reviewer :)

**Comment by swag** [comment]
@rose-huang should i merge this or wait for you to add the form component / card? Thank you!

**Comment by rose-huang** [comment]
@swag I can push changes to this PR and merge it in when it's ready!

**Pull request merged**
